#ifndef EDITOR_HPP
#define EDITOR_HPP 1

#include <QApplication>
#include <QMainWindow>
#include <QWindow>

#include <QMessageBox>
#include <QTextStream>
#include <QRegularExpression>

#include <QLabel>
#include<QTextEdit>
#include <QFileDialog>

#include <QFile>
#include <QDir>

#include<QIcon>
#include<QSize>

#include <QAction>

#include<QCommandLineParser>

#include "defines.hpp"
#include "config.hpp"

// autogenerated during compile
#include "ui_main.h"

/*!
 \class Editor
 \brief The main application class that controls all functionalities of the editor.

*/
class Editor{

private:
    int last_search_pos = 0;
    int line_count;
    int word_count;
    int char_count;
    QString current_file = "";
    bool is_saved = false;
    bool is_wrap = true;

    QApplication * app;
    QMainWindow * window;
    Ui::MainWindow * main;

    QIcon icon = QIcon(GIDUBA_ICON);

    void setup_file_actions();
    void setup_edit_actions();
    void setup_help_actions();
    void setup_search_replace();
    void setup_status_events();

    void setup_editor();

    void update_status();

    void reload_geom();
    void save_geom();

    Config * config;


public:
    Editor(int argc, char ** argv);
    int run();
};

#endif
